// rust-saas/frontend/vec-web/src/pages/Distillation/index.tsx
import { useState } from 'react';
import { Card, Table, Button, Tag, Modal, Select } from 'antd';
import { ShakeOutlined, PlayCircleOutlined } from '@ant-design/icons';
import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query';
import { documentApi } from '@/api/document';
import dayjs from 'dayjs';

const Distillation = () => {
  const [selectedDoc, setSelectedDoc] = useState<string>('');
  const [isModalVisible, setIsModalVisible] = useState(false);
  const queryClient = useQueryClient();

  const { data: documents } = useQuery({
    queryKey: ['documents'],
    queryFn: () => documentApi.list({ page_size: 100 }),
  });

  const { data: knowledgePoints } = useQuery({
    queryKey: ['knowledge-points', selectedDoc],
    queryFn: () => documentApi.getKnowledgePoints(selectedDoc),
    enabled: !!selectedDoc,
  });

  const distillMutation = useMutation({
    mutationFn: (id: string) => documentApi.distill(id),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['knowledge-points', selectedDoc] });
      setIsModalVisible(false);
    },
  });

  return (
    <div>
      <h1 className="text-2xl font-bold mb-6">知识蒸馏</h1>

      <Card className="mb-6">
        <div className="flex items-center gap-4">
          <Select
            placeholder="选择文档"
            style={{ width: 300 }}
            options={documents?.data.map((doc: { id: string; title: string }) => ({
              value: doc.id,
              label: doc.title,
            }))}
            onChange={(value) => setSelectedDoc(value)}
          />
          <Button
            type="primary"
            icon={<PlayCircleOutlined />}
            onClick={() => setIsModalVisible(true)}
            disabled={!selectedDoc}
          >
            触发蒸馏
          </Button>
        </div>
      </Card>

      {selectedDoc && knowledgePoints && (
        <Card
          title={
            <span className="flex items-center gap-2">
              <ShakeOutlined />
              知识要点列表
            </span>
          }
        >
          <Table
            dataSource={knowledgePoints}
            columns={[
              {
                title: '内容',
                dataIndex: 'content',
                key: 'content',
                ellipsis: true,
              },
              {
                title: '置信度',
                dataIndex: 'confidence',
                key: 'confidence',
                render: (confidence: number) => (
                  <Tag color={confidence > 0.8 ? 'green' : confidence > 0.5 ? 'orange' : 'red'}>
                    {(confidence * 100).toFixed(1)}%
                  </Tag>
                ),
              },
              {
                title: '关键词',
                dataIndex: 'keywords',
                key: 'keywords',
                render: (keywords: string[]) => (
                  <div className="flex flex-wrap gap-1">
                    {keywords.map((kw, idx) => (
                      <Tag key={idx}>{kw}</Tag>
                    ))}
                  </div>
                ),
              },
              {
                title: '创建时间',
                dataIndex: 'created_at',
                key: 'created_at',
                render: (date: string) => dayjs(date).format('YYYY-MM-DD HH:mm'),
              },
            ]}
            rowKey="id"
            pagination={{ pageSize: 10 }}
          />
        </Card>
      )}

      <Modal
        title="确认蒸馏"
        visible={isModalVisible}
        onCancel={() => setIsModalVisible(false)}
        onOk={() => distillMutation.mutate(selectedDoc)}
        confirmLoading={distillMutation.isPending}
      >
        <p>确定要对该文档进行知识蒸馏吗？</p>
        <p className="text-gray-500 text-sm mt-2">蒸馏过程可能需要一些时间，请耐心等待。</p>
      </Modal>
    </div>
  );
};

export default Distillation;

// rust-saas/frontend/acl-web/src/views/vec/Distillation.vue
<script setup lang="ts">
import { ref, onMounted } from 'vue'
import { Sparkles, PlayCircle } from 'lucide-vue-next'
import { ElMessage } from 'element-plus'
import { documentApi } from '@/vec/api'
import type { Document, KnowledgePoint } from '@/vec/types'
import { formatDate } from '@/vec/utils/date'

const selectedDoc = ref<number | ''>('')
const documents = ref<Document[]>([])
const knowledgePoints = ref<KnowledgePoint[]>([])
const loadingDocs = ref(false)
const loadingPoints = ref(false)
const dialogVisible = ref(false)
const distilling = ref(false)

const loadDocuments = async () => {
  loadingDocs.value = true
  try {
    const res = await documentApi.list({ page_size: 100 })
    documents.value = res.documents || []
  } finally {
    loadingDocs.value = false
  }
}

const loadKnowledgePoints = async () => {
  if (!selectedDoc.value) return
  loadingPoints.value = true
  try {
    knowledgePoints.value = await documentApi.getKnowledgePoints(selectedDoc.value)
  } finally {
    loadingPoints.value = false
  }
}

const handleDocChange = (value: number) => {
  selectedDoc.value = value
  loadKnowledgePoints()
}

const handleDistill = async () => {
  if (!selectedDoc.value) return
  distilling.value = true
  try {
    await documentApi.distill(selectedDoc.value)
    ElMessage.success('知识蒸馏已触发')
    dialogVisible.value = false
    await loadKnowledgePoints()
  } finally {
    distilling.value = false
  }
}

const getConfidenceType = (confidence: number) => {
  if (confidence > 0.8) return 'success'
  if (confidence > 0.5) return 'warning'
  return 'danger'
}

onMounted(loadDocuments)
</script>

<template>
  <div class="p-6">
    <div class="page-header">
      <div>
        <h1 class="page-title">知识蒸馏</h1>
        <p class="page-subtitle">从文档中提取知识要点</p>
      </div>
      <button class="btn btn-primary" :disabled="!selectedDoc" @click="dialogVisible = true">
        <PlayCircle class="w-4 h-4" />
        触发蒸馏
      </button>
    </div>

    <el-card class="mb-6">
      <el-select
        v-model="selectedDoc"
        placeholder="选择文档"
        style="width: 300px"
        :loading="loadingDocs"
        @change="handleDocChange"
      >
        <el-option
          v-for="doc in documents"
          :key="doc.id"
          :label="doc.topic || doc.title || `文档 #${doc.id}`"
          :value="doc.id"
        />
      </el-select>
    </el-card>

    <el-card v-if="selectedDoc" v-loading="loadingPoints">
      <template #header>
        <div class="flex items-center gap-2">
          <Sparkles class="w-4 h-4" />
          <span>知识要点列表</span>
        </div>
      </template>
      <el-table :data="knowledgePoints" row-key="id" style="width: 100%">
        <el-table-column prop="point_type" label="类型" width="120">
          <template #default="{ row }">
            <el-tag type="info">{{ row.point_type || '-' }}</el-tag>
          </template>
        </el-table-column>
        <el-table-column prop="point_content" label="内容" show-overflow-tooltip />
        <el-table-column prop="confidence" label="置信度" width="120">
          <template #default="{ row }">
            <el-tag :type="getConfidenceType(row.confidence)">{{ ((row.confidence || 0) * 100).toFixed(1) }}%</el-tag>
          </template>
        </el-table-column>
        <el-table-column prop="created_at" label="创建时间" width="160">
          <template #default="{ row }">{{ formatDate(row.created_at, true) }}</template>
        </el-table-column>
      </el-table>
    </el-card>

    <el-dialog v-model="dialogVisible" title="确认蒸馏" width="400px">
      <p>确定要对该文档进行知识蒸馏吗？</p>
      <p class="text-gray-500 text-sm mt-2">蒸馏过程可能需要一些时间，请耐心等待。</p>
      <template #footer>
        <el-button @click="dialogVisible = false">取消</el-button>
        <el-button type="primary" :loading="distilling" @click="handleDistill">确定</el-button>
      </template>
    </el-dialog>
  </div>
</template>
