// rust-saas/frontend/vec-web/src/pages/Version/index.tsx
import { useState } from 'react';
import { Card, Select, Table, Button, Tag, Modal } from 'antd';
import { HistoryOutlined, RollbackOutlined, CompressOutlined } from '@ant-design/icons';
import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query';
import { documentApi } from '@/api/document';
import { versionApi } from '@/api/version';
import type { Version } from '@/types/version';
import dayjs from 'dayjs';

const VersionPage = () => {
  const [selectedDoc, setSelectedDoc] = useState<string>('');
  const queryClient = useQueryClient();

  const { data: documents } = useQuery({
    queryKey: ['documents'],
    queryFn: () => documentApi.list({ page_size: 100 }),
  });

  const { data: versions } = useQuery({
    queryKey: ['versions', selectedDoc],
    queryFn: () => versionApi.list(selectedDoc),
    enabled: !!selectedDoc,
  });

  const rollbackMutation = useMutation({
    mutationFn: (data: { documentId: string; versionNumber: number }) =>
      versionApi.rollback(data.documentId, data.versionNumber),
    onSuccess: () => queryClient.invalidateQueries({ queryKey: ['versions', selectedDoc] }),
  });

  const handleRollback = (versionNumber: number) => {
    Modal.confirm({
      title: '确认回滚',
      content: `确定要回滚到版本 ${versionNumber} 吗？`,
      onOk: () => rollbackMutation.mutate({ documentId: selectedDoc, versionNumber }),
    });
  };

  return (
    <div>
      <h1 className="text-2xl font-bold mb-6">版本管理</h1>

      <Card className="mb-6">
        <Select
          placeholder="选择文档"
          style={{ width: 300 }}
          options={documents?.data.map((doc: { id: string; title: string; version: number }) => ({
            value: doc.id,
            label: `${doc.title} (v${doc.version})`,
          }))}
          onChange={(value) => setSelectedDoc(value)}
        />
      </Card>

      {selectedDoc && versions && (
        <Card
          title={
            <span className="flex items-center gap-2">
              <HistoryOutlined />
              版本列表
            </span>
          }
          extra={<Button icon={<CompressOutlined />}>对比版本</Button>}
        >
          <Table
            dataSource={versions}
            columns={[
              {
                title: '版本号',
                dataIndex: 'version_number',
                key: 'version_number',
                render: (num: number) => <Tag color="blue">v{num}</Tag>,
              },
              {
                title: '标题',
                dataIndex: 'title',
                key: 'title',
              },
              {
                title: '状态',
                dataIndex: 'status',
                key: 'status',
                render: (status: string) => (
                  <Tag
                    color={
                      status === 'completed'
                        ? 'success'
                        : status === 'processing'
                        ? 'processing'
                        : 'error'
                    }
                  >
                    {status}
                  </Tag>
                ),
              },
              {
                title: '变更摘要',
                dataIndex: 'change_summary',
                key: 'change_summary',
                ellipsis: true,
              },
              {
                title: '创建时间',
                dataIndex: 'created_at',
                key: 'created_at',
                render: (date: string) => dayjs(date).format('YYYY-MM-DD HH:mm'),
              },
              {
                title: '操作',
                key: 'actions',
                render: (_: unknown, record: Version) => (
                  <div className="flex gap-2">
                    <Button
                      type="link"
                      icon={<RollbackOutlined />}
                      onClick={() => handleRollback(record.version_number)}
                    >
                      回滚
                    </Button>
                  </div>
                ),
              },
            ]}
            rowKey="id"
            pagination={{ pageSize: 10 }}
          />
        </Card>
      )}
    </div>
  );
};

export default VersionPage;

// rust-saas/frontend/acl-web/src/views/vec/Version.vue
<script setup lang="ts">
import { ref, onMounted } from 'vue'
import { History, RotateCcw, GitCompare } from 'lucide-vue-next'
import { ElMessage, ElMessageBox } from 'element-plus'
import { documentApi, versionApi } from '@/vec/api'
import type { Document, Version } from '@/vec/types'
import { formatDate } from '@/vec/utils/date'

const selectedDoc = ref('')
const documents = ref<Document[]>([])
const versions = ref<Version[]>([])
const loadingDocs = ref(false)
const loadingVersions = ref(false)
const rollingBackId = ref<string | null>(null)

const loadDocuments = async () => {
  loadingDocs.value = true
  try {
    const res = await documentApi.list({ page_size: 100 })
    documents.value = res.documents || []
  } finally {
    loadingDocs.value = false
  }
}

const loadVersions = async () => {
  if (!selectedDoc.value) return
  loadingVersions.value = true
  try {
    versions.value = await versionApi.list(selectedDoc.value)
  } catch {
    versions.value = []
  } finally {
    loadingVersions.value = false
  }
}

const handleDocChange = (value: string) => {
  selectedDoc.value = value
  loadVersions()
}

const handleRollback = async (version: Version) => {
  try {
    await ElMessageBox.confirm(`确定要回滚到版本 ${version.version_number} 吗？`, '提示', { type: 'warning' })
    rollingBackId.value = version.id
    await versionApi.rollback(selectedDoc.value, Number(version.id))
    ElMessage.success('回滚成功')
    await loadVersions()
  } catch {
    // cancelled
  } finally {
    rollingBackId.value = null
  }
}

const getStatusType = (status: string) => {
  if (status === 'completed') return 'success'
  if (status === 'processing') return 'warning'
  return 'danger'
}

onMounted(loadDocuments)
</script>

<template>
  <div class="p-6">
    <div class="page-header">
      <div>
        <h1 class="page-title">版本管理</h1>
        <p class="page-subtitle">查看与回滚文档版本</p>
      </div>
    </div>

    <el-card class="mb-6">
      <el-select
        v-model="selectedDoc"
        placeholder="选择文档"
        style="width: 300px"
        :loading="loadingDocs"
        @change="handleDocChange"
      >
        <el-option
          v-for="doc in documents"
          :key="doc.id"
          :label="`${doc.topic || doc.title || '文档 #' + doc.id} (v${doc.version || 0})`"
          :value="doc.id"
        />
      </el-select>
    </el-card>

    <el-card v-if="selectedDoc" v-loading="loadingVersions">
      <template #header>
        <div class="flex items-center justify-between">
          <div class="flex items-center gap-2">
            <History class="w-4 h-4" />
            <span>版本列表</span>
          </div>
          <el-button :icon="GitCompare" size="small">对比版本</el-button>
        </div>
      </template>
      <el-table :data="versions" row-key="id" style="width: 100%">
        <el-table-column prop="version_number" label="版本号" width="100">
          <template #default="{ row }">
            <el-tag type="primary">v{{ row.version_number }}</el-tag>
          </template>
        </el-table-column>
        <el-table-column prop="title" label="标题" show-overflow-tooltip />
        <el-table-column prop="status" label="状态" width="100">
          <template #default="{ row }">
            <el-tag :type="getStatusType(row.status)">{{ row.status }}</el-tag>
          </template>
        </el-table-column>
        <el-table-column prop="change_summary" label="变更摘要" show-overflow-tooltip />
        <el-table-column prop="created_at" label="创建时间" width="160">
          <template #default="{ row }">{{ formatDate(row.created_at, true) }}</template>
        </el-table-column>
        <el-table-column label="操作" width="120">
          <template #default="{ row }">
            <el-button link type="primary" :icon="RotateCcw" :loading="rollingBackId === row.id" @click="handleRollback(row)">回滚</el-button>
          </template>
        </el-table-column>
      </el-table>
    </el-card>
  </div>
</template>
