// rust-saas/frontend/acl-web/src/views/vec/Task.vue
<script setup lang="ts">
import { ref, onMounted } from 'vue'
import { Clock, PauseCircle, CheckCircle, XCircle, AlertCircle, RefreshCw } from 'lucide-vue-next'
import { ElMessage, ElMessageBox } from 'element-plus'
import { taskApi, documentApi } from '@/vec/api'
import type { Task, Document } from '@/vec/types'
import { formatDate } from '@/vec/utils/date'

const tasks = ref<Task[]>([])
const documents = ref<Document[]>([])
const loading = ref(false)

const loadData = async () => {
  loading.value = true
  try {
    const [taskList, docList] = await Promise.all([
      taskApi.list(),
      documentApi.list({ page_size: 100 }),
    ])
    tasks.value = taskList.tasks || []
    documents.value = docList.documents || []
  } finally {
    loading.value = false
  }
}

const getStatusIcon = (status: string) => {
  switch (status) {
    case 'pending':
      return Clock
    case 'processing':
      return PauseCircle
    case 'completed':
      return CheckCircle
    case 'failed':
      return XCircle
    default:
      return AlertCircle
  }
}

const getStatusType = (status: string) => {
  switch (status) {
    case 'completed':
      return 'success'
    case 'processing':
      return 'warning'
    case 'failed':
      return 'danger'
    default:
      return 'info'
  }
}

const taskTypeMap: Record<string, string> = {
  document_process: '文档处理',
  document_reindex: '重新索引',
  document_distill: '知识蒸馏',
  batch_process: '批量处理',
}

const getTaskTypeLabel = (type?: string) => {
  return (type && taskTypeMap[type]) || type || '未知'
}

const getDocumentId = (row: Task) => {
  if (row.document_id) return row.document_id
  const payload = row.payload
  if (payload && typeof payload === 'object') {
    const id = payload.document_id
    if (id !== undefined && id !== null) return String(id)
  }
  return undefined
}

const getDocumentTitle = (documentId?: string) => {
  if (!documentId) return '-'
  const doc = documents.value.find((d) => String(d.id) === String(documentId))
  return doc?.topic || doc?.title || `文档 #${documentId}`
}

const handleCancel = async (row: Task) => {
  if (row.status === 'completed') return
  try {
    await ElMessageBox.confirm('确定要取消该任务吗？', '提示', { type: 'warning' })
    await taskApi.cancel(String(row.id))
    ElMessage.success('任务已取消')
    loadData()
  } catch (error: any) {
    if (error !== 'cancel') {
      ElMessage.error(error?.message || '取消任务失败')
    }
  }
}

onMounted(loadData)
</script>

<template>
  <div class="p-6">
    <div class="page-header">
      <div>
        <h1 class="page-title">任务管理</h1>
        <p class="page-subtitle">查看文档处理、重新索引等异步任务</p>
      </div>
      <button class="btn btn-outline" :disabled="loading" @click="loadData">
        <RefreshCw class="w-4 h-4" />
        刷新
      </button>
    </div>

    <el-card v-loading="loading">
      <template #header>
        <div class="flex items-center gap-2">
          <Clock class="w-4 h-4" />
          <span>任务列表</span>
        </div>
      </template>
      <el-table :data="tasks" row-key="id" style="width: 100%" empty-text="暂无任务">
        <el-table-column label="任务ID" width="80" show-overflow-tooltip>
          <template #default="{ row }">{{ row.id }}</template>
        </el-table-column>
        <el-table-column prop="task_type" label="任务类型" width="130">
          <template #default="{ row }">
            <el-tag type="primary">{{ getTaskTypeLabel(row.task_type) }}</el-tag>
          </template>
        </el-table-column>
        <el-table-column label="关联文档" min-width="160">
          <template #default="{ row }">{{ getDocumentTitle(getDocumentId(row)) }}</template>
        </el-table-column>
        <el-table-column prop="status" label="状态" width="140">
          <template #default="{ row }">
            <span class="flex items-center gap-2">
              <component :is="getStatusIcon(row.status)" class="w-4 h-4" />
              <el-tag :type="getStatusType(row.status)">{{ row.status }}</el-tag>
            </span>
          </template>
        </el-table-column>
        <el-table-column prop="progress" label="进度" width="180">
          <template #default="{ row }">
            <el-progress :percentage="Math.round(row.progress || 0)" size="small" />
          </template>
        </el-table-column>
        <el-table-column prop="created_at" label="创建时间" width="160">
          <template #default="{ row }">{{ formatDate(row.created_at, true) }}</template>
        </el-table-column>
        <el-table-column prop="message" label="消息" min-width="160" show-overflow-tooltip />
        <el-table-column label="操作" width="100">
          <template #default="{ row }">
            <el-button
              link
              type="danger"
              :disabled="row.status === 'completed' || row.status === 'failed'"
              @click="handleCancel(row)"
            >
              取消
            </el-button>
          </template>
        </el-table-column>
      </el-table>
    </el-card>
  </div>
</template>

// rust-saas/frontend/vec-web/src/pages/Task/index.tsx
import { Card, Table, Tag, Progress, Button } from 'antd';
import { ClockCircleOutlined, PauseCircleOutlined, CheckCircleOutlined, CloseCircleOutlined } from '@ant-design/icons';
import { useQuery } from '@tanstack/react-query';
import { taskApi } from '@/api/task';
import { documentApi } from '@/api/document';
import type { Task } from '@/types/task';
import dayjs from 'dayjs';

const TaskPage = () => {
  const { data: tasks } = useQuery({
    queryKey: ['tasks'],
    queryFn: () => taskApi.list(),
  });

  const { data: documents } = useQuery({
    queryKey: ['documents'],
    queryFn: () => documentApi.list({ page_size: 100 }),
  });

  const getStatusIcon = (status: string) => {
    switch (status) {
      case 'pending':
        return <ClockCircleOutlined className="text-gray-400" />;
      case 'running':
        return <PauseCircleOutlined className="text-blue-500" />;
      case 'completed':
        return <CheckCircleOutlined className="text-green-500" />;
      case 'failed':
        return <CloseCircleOutlined className="text-red-500" />;
      default:
        return null;
    }
  };

  return (
    <div>
      <h1 className="text-2xl font-bold mb-6">任务管理</h1>

      <Card
        title={
          <span className="flex items-center gap-2">
            <ClockCircleOutlined />
            任务列表
          </span>
        }
      >
        <Table<Task>
          dataSource={tasks}
          columns={[
            {
              title: '任务ID',
              dataIndex: 'id',
              key: 'id',
              ellipsis: true,
            },
            {
              title: '任务类型',
              dataIndex: 'task_type',
              key: 'task_type',
              render: (type: string) => <Tag color="blue">{type}</Tag>,
            },
            {
              title: '关联文档',
              key: 'document',
              render: (_: unknown, record: Task) => {
                const doc = documents?.data.find((d: { id: string }) => d.id === record.document_id);
                return doc?.title || '未知';
              },
            },
            {
              title: '状态',
              dataIndex: 'status',
              key: 'status',
              render: (status: string) => (
                <span className="flex items-center gap-2">
                  {getStatusIcon(status)}
                  <Tag
                    color={
                      status === 'completed'
                        ? 'success'
                        : status === 'running'
                        ? 'processing'
                        : status === 'failed'
                        ? 'error'
                        : 'default'
                    }
                  >
                    {status}
                  </Tag>
                </span>
              ),
            },
            {
              title: '进度',
              dataIndex: 'progress',
              key: 'progress',
              render: (progress: number) => <Progress percent={progress} size="small" />,
            },
            {
              title: '创建时间',
              dataIndex: 'created_at',
              key: 'created_at',
              render: (date: string) => dayjs(date).format('YYYY-MM-DD HH:mm'),
            },
            {
              title: '更新时间',
              dataIndex: 'updated_at',
              key: 'updated_at',
              render: (date: string) => dayjs(date).format('YYYY-MM-DD HH:mm'),
            },
            {
              title: '操作',
              key: 'actions',
              render: (_: unknown, record: Task) => (
                <Button
                  type="link"
                  danger
                  disabled={record.status === 'completed'}
                >
                  取消
                </Button>
              ),
            },
          ]}
          rowKey="id"
          pagination={{ pageSize: 10 }}
        />
      </Card>
    </div>
  );
};

export default TaskPage;
